### ISSUE TITLE
27 à 30/08/2018: 4ª Semana da Computação da UFRJ

### ISSUE THREAD

**Issue by leogoncalves** [hi-hi-ray/eventos-ti-rj#11]
**Local**:  Av. Athos da Silveira Ramos, 274, Rio de Janeiro
**Horário** : 08:00 às 17:00
**URL**: https://www.facebook.com/SemanaDaComputacaoUFRJ/
**Observações**:
**Descrição**: A Semana da Computação é um evento multidisciplinar que busca trazer conteúdo das mais diversas áreas relacionadas a computação. Teremos palestras de representantes de empresas, estudantes, ex-estudantes e professores.

**Comment by leogoncalves** [comment]
Esqueci de comentar, mas o evento é gratuito. Não sei se existe um label pra isso.

**Comment by hi-hi-ray** [comment]
Por padrão eu deixo como eventos gratuitos, ai por isso não existe label.
