### ISSUE TITLE
04/09/2018: Vue.JS in Rio - III

### ISSUE THREAD

**Issue by claudiolcastro** [hi-hi-ray/eventos-ti-rj#18]
https://www.meetup.com/pt-BR/Vue-js-in-Rio/events/253671722/

**terça-feira, 4 de setembro de 2018
19:30 até 22:00**

**B2W Digital
Rua Sacadura Cabral, 130 · Rio de Janeiro**

O que vamos fazer

Talk (in english):
> Live Coding, tests in Vue.JS
> Eduardo [posva]
(Vue.JS Core Team e organizador do Meetup Vue.JS in Paris)

Talk:
> Criando e publicando sua biblioteca de componentes no NPM
> Gabriel Mule

Talk:
> PWA e Web Components - Vendo o futuro aprender com o passado
> Paulo Marinho

-- Envie sua talk https://goo.gl/forms/uIDjwX0JSfr0X2gX2

• Informações importantes
- Favor chegar 30min antes para evitar gargalos na portaria do prédio.
- Levar identidade para apresentação na entrada.

**Comment by hi-hi-ray** [comment]
@claudiolcastro Poderia só por o local e o horário, por favor?
